In [ ]:
#Import Library pandas numpy
import pandas as pd
import numpy as np

In [ ]:
#Import data dari GDrive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Ambil data tes_techno.csv dari gdrive
test_techno = pd.read_csv('/content/gdrive/MyDrive/Techno/TechnoLomba/test_techno.csv')
test_techno.head()

battery_power  blue  clock_speed  dual_sim  ...  three_g  touch_screen  wifi  id
0            709     0          1.9         0  ...        1             1     1   1
1           1744     0          2.8         0  ...        1             0     0   2
2           1314     1          2.2         0  ...        1             1     1   3
3           1136     0          0.5         0  ...        1             0     1   4
4           1039     1          2.7         0  ...        0             1     1   5

[5 rows x 21 columns]

In [ ]:
data = [1,3,5,7]
data.append([2,4,6,8])
print(len(data))

5


In [ ]:
for i in range(1,3):
  print(i)
for j in range(2):
  print(j)

1
2
0
1


In [ ]:
#Ambil data train_techno.csv dari gdrive
train_techno = pd.read_csv('/content/gdrive/MyDrive/Techno/TechnoLomba/train_techno.csv')
train_techno.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [ ]:
 test_techno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818 entries, 0 to 817
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  818 non-null    int64  
 1   blue           818 non-null    int64  
 2   clock_speed    818 non-null    float64
 3   dual_sim       818 non-null    int64  
 4   fc             818 non-null    int64  
 5   four_g         818 non-null    int64  
 6   int_memory     818 non-null    int64  
 7   m_dep          818 non-null    float64
 8   mobile_wt      818 non-null    int64  
 9   n_cores        818 non-null    int64  
 10  pc             818 non-null    int64  
 11  px_height      818 non-null    int64  
 12  px_width       818 non-null    int64  
 13  ram            818 non-null    int64  
 14  sc_h           818 non-null    int64  
 15  sc_w           818 non-null    int64  
 16  talk_time      818 non-null    int64  
 17  three_g        818 non-null    int64  
 18  touch_scre

In [ ]:
train_techno.describe()

battery_power         blue  ...         wifi  price_range
count    1182.000000  1182.000000  ...  1182.000000  1182.000000
mean     1248.247885     0.483080  ...     0.519459     1.537225
std       440.202286     0.499925  ...     0.499833     1.125436
min       501.000000     0.000000  ...     0.000000     0.000000
25%       853.250000     0.000000  ...     0.000000     1.000000
50%      1260.000000     0.000000  ...     1.000000     2.000000
75%      1631.000000     1.000000  ...     1.000000     3.000000
max      1997.000000     1.000000  ...     1.000000     3.000000

[8 rows x 21 columns]

In [ ]:
#Ambil data X dan y
X = train_techno.iloc[:,0:20].values
y = train_techno.loc[:, ['price_range']].values

[[8.420e+02 0.000e+00 2.200e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [1.021e+03 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [5.630e+02 1.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 ...
 [1.880e+03 0.000e+00 5.000e-01 ... 1.000e+00 1.000e+00 0.000e+00]
 [1.479e+03 1.000e+00 1.800e+00 ... 1.000e+00 0.000e+00 0.000e+00]
 [1.271e+03 0.000e+00 1.500e+00 ... 0.000e+00 1.000e+00 0.000e+00]]


In [ ]:
print(X.shape)
print(y.shape)

(1182, 20)
(1182, 1)


In [ ]:
#Import KNeighborsClassifier,DecisionTreeClassifier,RandomForestClassifier, dan SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
#Import KFold dan cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

In [ ]:
#KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 3)
scoring = 'accuracy'
score = cross_val_score(clf, X, y.ravel(), cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[0.86554622 0.88235294 0.90677966 0.87288136 0.93220339 0.91525424
 0.91525424 0.96610169 0.94067797 0.88135593]


In [ ]:
#Random KNeighbors Score
round(np.mean(score)*100, 2)

90.78

In [ ]:
#DecisionTreeClassifier
clf = DecisionTreeClassifier()
scoring = 'accuracy'
score = cross_val_score(clf, X, y.ravel(), cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[0.78151261 0.81512605 0.8220339  0.81355932 0.78813559 0.77118644
 0.81355932 0.80508475 0.86440678 0.78813559]


In [ ]:
#Random DecisionTree Score
round(np.mean(score)*100, 2)

80.63

In [ ]:
#RandomForestClassifier
clf = RandomForestClassifier(n_estimators=13)
scoring = 'accuracy'
score = cross_val_score(clf, X, y.ravel(), cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[0.73109244 0.81512605 0.80508475 0.77118644 0.77118644 0.80508475
 0.83050847 0.8220339  0.80508475 0.8220339 ]


In [ ]:
#Random Forest Score
round(np.mean(score)*100, 2)

79.78

In [ ]:
#SVMClassifier
clf = SVC()
scoring = 'accuracy'
score = cross_val_score(clf, X, y.ravel(), cv=k_fold,n_jobs= 1,  scoring=scoring)
print(score)

[0.90756303 0.94117647 0.97457627 0.91525424 0.93220339 0.97457627
 0.93220339 0.96610169 0.97457627 0.94915254]


In [ ]:
#Random SVM Score
round(np.mean(score)*100, 2)

94.67

In [ ]:
#Ubah variabel X menjadi X_train dan y menjadi y_train
X_train = X
y_train = y


(1182, 20)
(818, 20)


In [ ]:
#Karena SVM yang paling besar
from sklearn.svm import SVC      
classifier = SVC()
classifier.fit(X_train, y_train.ravel()) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
#nilai y untuk test_techno
X_valid =  test_techno.iloc[:,0:20].values
y_pred = classifier.predict(X_valid)

In [ ]:
#Import test_sol dari gdrive
test_sol = pd.read_csv('/content/gdrive/MyDrive/Techno/TechnoLomba/test_sol.csv')

In [ ]:
#Masukkan value y_pred ke price_range
test_sol['price_range'] = y_pred
test_sol.to_csv(r'/content/gdrive/MyDrive/Techno/TechnoLomba/test_sol.csv',index = False)

#Test file yang sudah dimasukkan
print(test_sol[:10])

   Id  price_range
0   1            0
1   2            0
2   3            3
3   4            2
4   5            2
5   6            0
6   7            3
7   8            2
8   9            0
9  10            3
